
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://tvqyozyjqcswojsbduzw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2cXlvenlqcWNzd29qc2JkdXp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI5MDU2MjIsImV4cCI6MjA0ODQ4MTYyMn0.f3pTfJsm94Rj0CDLSmKvmP-s30CQ0LQh7s5s1dopvwI";

// Function to determine storage type based on remember me preference
const getStorageType = () => {
  const rememberMe = localStorage.getItem('supabase_remember_me');
  const expiresAt = localStorage.getItem('supabase_remember_me_expires');
  
  // Check if remember me is set and not expired
  if (rememberMe === 'true' && expiresAt) {
    const expiryDate = new Date(expiresAt);
    const now = new Date();
    
    if (now < expiryDate) {
      return localStorage;
    } else {
      // Clean up expired remember me preference
      localStorage.removeItem('supabase_remember_me');
      localStorage.removeItem('supabase_remember_me_expires');
    }
  }
  
  return sessionStorage;
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: getStorageType(),
    persistSession: true,
    autoRefreshToken: true,
  }
});
